matrix:
  fast_finish: true
  include:
    - sudo: required
    - os: osx
      env: BUILD=wheels PYTHON_VERSION=2.7.13 PIP_USER=1


cache:
  pip

install:
  - pip install --upgrade pip
  - pip install cython
  - make
  - pip install cibuildwheel==0.2.1
  - cibuildwheel --output-dir wheelhouse
  
script:
  - make
