language: generic

env:
  global:
    - PYMODULE: httpparser
    - RELEASE_PYTHON_VERSIONS: "2.7 3.5 3.6"
    - TWINE_USERNAME: dontcare
    - TWINE_REPOSITORY: httpparser
    - TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
    - CIBW_SKIP="cp26-* cp33-* cp34*"
    - CIBW_OUPUT_DIR="dist/"

matrix:
  fast_finish: true
  include:
    - os: osx
      env:
        - CIBW_BEFORE_BUILD="sh -c 'python -m pip install cython && make'"
      #before_install:
      #  - python -m pip install pip --upgrade
      #  - python -m pip install cython
      #  - python -m pip install twine
      #  - make
      #install:
      #  - python -m pip install pip --upgrade
      #  - python -m pip install cibuildwheel
      #  - python -m pip install twine
      #  - make
      script:
        - python -m pip install pip --upgrade
        - python -m pip install cibuildwheel
        - cibuildwheel --platform macos --output-dir $CIBW_OUPUT_DIR
        - python -m pip install twine
        - python -m pip install cython
        - make
        - python setup.py sdist
        - python -m twine upload dist/*.whl dist/*.tar.*
      #after_script:
      #  #- python -m pip install twine
      #  - python setup.py sdist
      #  - python -m twine upload dist/*.whl dist/*.tar.*

      
    #- os: linux
    #  sudo: false
    #  dist: trusty
    #  language: python
    #  python: "2.7.13"
    #  services: [docker]
    #  env:
    #    - CIBW_BEFORE_BUILD="pip install cython && make"
    #    - BUILD=wheels,release
    #    - PYTHON_VERSION=2.7.13
    #  install:
    #    - pip install cibuildwheel
    #    - pip install twine
    #  script:
    #    - cibuildwheel --platform linux --output-dir $CIBW_OUPUT_DIR
    #  after_success:
    #    - python -m twine upload dist/*.whl

cache:
  pip

#after_success:
#  - python setup.py sdist
#  - python -m twine upload dist/*.tar.*
