language: generic

env:
  global:
    - PYMODULE: httpparser
    - RELEASE_PYTHON_VERSIONS: "2.7 3.4 3.5 3.6"
    - TWINE_USERNAME: dontcare
    - TWINE_REPOSITORY: httpparser
    - TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
    - CIBW_SKIP="cp26-* cp33-* cp34-* cp35-* cp36-*"
    - CIBW_BEFORE_BUILD="python -m pip install cython && make"

matrix:
  fast_finish: true
  include:
    - os: osx
      env:
        PLATFORM=macos
      #language: python
      #python: "2.7.13"
      
    #- os: linux
    #  dist: trusty
    #  sudo: true
    #  language: python
    #  python: "2.7.13"
    #  env:
    #      BUILD=wheels,release
    #      PYTHON_VERSION=2.7.13
    #      PLATFORM=linux


install:
  - pip install --upgrade pip
  - pip install cython
  - pip install cibuildwheel

script:
  - ./ci/cibuild_before.sh
  #- cibuildwheel --platform $PLATFORM --output-dir wheelhouse

