language: generic

env:
  global:
    - PYMODULE: httpparser
    - RELEASE_PYTHON_VERSIONS: "2.7 3.4 3.5 3.6"
    - TWINE_USERNAME: dontcare
    - TWINE_REPOSITORY: httpparser
    - TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
    - CIBW_SKIP="cp26-* cp33-* *i386* *i686*"
    - CIBW_OUPUT_DIR="dist/"

matrix:
  fast_finish: true
  include:
    #- os: osx
    #  before_install:
    #    - python -m pip install pip --upgrade
    #    - python -m pip install cython
    #    - make
    #  install:
    #    - pip install cibuildwheel
    #  script:
    #    - cibuildwheel --platform macos --output-dir $CIBW_OUPUT_DIR
      
    - os: linux
      dist: trusty
      sudo: false
      language: python
      python: "2.7.13"
      #services: [docker]
      env:
        - CIBW_BEFORE_BUILD=""
        - BUILD=wheels,release
        - PYTHON_VERSION=2.7.13
      install:
        - pip install --upgrade pip
        - pip install cython
        - pip install cibuildwheel
      script:
        - make
        - cibuildwheel --platform linux --output-dir $CIBW_OUPUT_DIR
