language: generic

matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx
      sudo: true
      language: python
      python: "3.6.1"
    - os: linux
      sudo: true
      language: python
      python: "3.6.1"

env:
  global:
    - TWINE_USERNAME=dontcare

script:
  - pip install cibuildwheel cython
  - make
  - cibuildwheel --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      python -m pip install twine
      python -m twine upload wheelhouse/*.whl -r https://pypi.python.org/pypi/httpparser
    fi
