language: generic

matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx
    - os: linux

env:
  global:
    - TWINE_USERNAME=dontcare

script:
  - pip install cibuildwheel cython
  - make
  - cibuildwheel --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      python -m pip install twine
      python -m twine upload wheelhouse/*.whl
    fi
