language: generic

env:
  global:
    - PYMODULE: httpparser
    - RELEASE_PYTHON_VERSIONS: "2.7 3.4 3.5 3.6"
    - TWINE_USERNAME: dontcare
    - TWINE_REPOSITORY: httpparser
    - TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
    - CIBW_SKIP="cp26-* cp33-* manylinux1_i386* manylinux1_i686*"

matrix:
  fast_finish: true
  include:
    - os: osx
      before_install:
        - python -m pip install pip --upgrade
        - python -m pip install cython
        - make
      script:
        - cibuildwheel --platform macos --output-dir dist/
      
    - os: linux
      dist: trusty
      sudo: false
      language: python
      python: "2.7.13"
      services: [docker]
      env:
          BUILD=wheels,release
          PYTHON_VERSION=2.7.13
          PLATFORM=linux
      install:
        - pip install --upgrade pip
        - pip install cython
        - pip install cibuildwheel
      script:
        - make
        - cibuildwheel --platform linux --output-dir dist/
