language: generic

env:
  global:
    - PYMODULE: httpparser
    - RELEASE_PYTHON_VERSIONS: "2.7 3.4 3.5 3.6"
    - TWINE_USERNAME: dontcare
    - TWINE_REPOSITORY: httpparser
    - TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
    - CIBW_SKIP="cp26-* cp33-* manylinux1_i386"

matrix:
  fast_finish: true
  include:
    - os: osx
      env:
        - PLATFORM=macos
      before_install:
        - python -m pip install pip --upgrade
        - python -m pip install cython
        - make
      
    - os: linux
      dist: trusty
      sudo: false
      language: python
      python: "2.7.13"
      services: [docker]
      env:
          BUILD=wheels,release
          PYTHON_VERSION=2.7.13
          PLATFORM=linux
      before_install:
        - python -m pip install pip --upgrade
        - python -m pip install cython
        - make


install:
  - pip install cibuildwheel

script:
  - cibuildwheel --platform $PLATFORM --output-dir dist/
