language: generic

env:
  global:
    - PYMODULE: httpparser
    - RELEASE_PYTHON_VERSIONS: "2.7 3.4 3.5 3.6"
    - TWINE_USERNAME: dontcare
    - TWINE_REPOSITORY: httpparser
    - TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
    - CIBW_BEFORE_BUILD: .ci/cibuild_before.sh

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      sudo: true
      language: python
      python: "2.7.13"
      env: BUILD=wheels,release PYTHON_VERSION=2.7.13


install:
  - pip install --upgrade pip
  - pip install cython
  - pip install cibuildwheel

script:
  - cibuildwheel --output-dir wheelhouse

