language: generic

env:
  global:
    - PYMODULE=uvloop
    - RELEASE_PYTHON_VERSIONS="2.7 3.4 3.5 3.6"

matrix:
  fast_finish: true
  include:
    - os: osx
      env: BUILD=wheels PYTHON_VERSION=2.7.13 PIP_USER=1

    - os: osx
      env: BUILD=wheels PYTHON_VERSION=3.5.3 PIP_USER=1

    - os: osx
      env: BUILD=wheels PYTHON_VERSION=3.6.1 PIP_USER=1

    - os: linux
      dist: trusty
      sudo: false
      language: python
      python: "2.7.13"
      services: [docker]
      env: BUILD=wheels,release

    - os: linux
      dist: trusty
      sudo: false
      language: python
      python: "3.5.3"
      services: [docker]
      env: BUILD=wheels,release

    - os: linux
      dist: trusty
      sudo: false
      language: python
      python: "3.6.1"
      services: [docker]
      env: BUILD=wheels,release

env:
  global:
    - TWINE_USERNAME=dontcare

script:
  - pip install --upgrade pip
  - pip install cython
  - make
